CREATE TABLE IF NOT EXISTS games (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(120) NOT NULL,
  platform VARCHAR(40) NOT NULL,
  notes TEXT NULL,
  cover_url VARCHAR(255) NULL,
  favorite TINYINT(1) NOT NULL DEFAULT 0,
  played TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
